/* this is an example config file */

LibraryPath= ~/Music
LibraryPath = ./test*dir
LibraryPath = ./dir{ 14 * 3 }
LibraryPath = ./dir\{14*3}
LibraryPath = ./dir\test\            
LibraryPath = ./dir\\test
LibraryPath =\\.test
LibraryPath = ./testing ending whitespace                               
LibraryPath = \testing-back-ws
LibraryPath = ./[dir1, \[dir2\, \[dir3\]\] ]/[ file1, file2, file3, ]/
LibraryPath = ./test dir

TopDecayRate = {  3 + [5, 6, 7] }
TopDecayRate = {  3 + [[4, 5] , 6, 7] }
TopDecayRate = {  3 + [[[4], 5, ]] }
TopDecayRate = {  [5, {5+2}] *  ( 3 + [4, 5, [6, 7]]) }
TopDecayRate = {  3 + [4] }
TopDecayRate = {  [3] + 4 }
TopDecayRate =   -([4, 5, [6, 7]] + 3) 
TopDecayRate = {  -(5/19) }
