/* Longhorn Configuration File */

/* Library Paths */
LibraryPath = ~/Music
/*
/* Unused Library Paths */
LibraryPath = ~/unused/path/1
LibraryPath = ~/unused/path/2
LibraryPath = ~/unused/path/3
*/

/* Settings */
/* Ints */
MaxHistory = 100
TopSongsLen = 500
TopAlbumsLen = 100
TopArtistsLen = 20

/* Floats */
TopDecayRate = 7 / 10
