/* Longhorn Configuration File */
/* Library Paths */
LibraryPath = ~/Music
/*
LibraryPath = ~/unused/path/1
LibraryPath = ~/unused/path/2
LibraryPath = ~/unused/path/3
*/
/* Settings */
MaxHistory = 100
TopSongsLen = 500
TopAlbumsLen = 100
TopArtistsLen = 20
TopDecayRate = 7 / 10
