/* This File Has Syntax Errors */

LibraryPath =
LibraryPath = ~/Music[5, 6
LibraryPath = ~/Music[5, 6, ,]
= ~/Music[5, 6, ] 

TopAlbumLen = 5
TopAlbumsLen = string
TopDecayRate = {  3 + [5, 6, 7] 
TopDecayRate =  3 + [5, 6, 7] )
